# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a6337b125de65bb17924b691b33f7afbc3c1cf09f53e0ada7d13ec9cdf5775fff8c4c5407cd6f7c79f711908a408917a6209b58a4fc776fdaeb1d4dadfbae23

test:
  secret_key_base: feaa4f35ca2871a705073ebbfd66d70d35b043d23201dab6e47cabb7c07d9dc110ab96bdc982e78396d991172c1e99c56b9aca5d1c7ea3b35119619345065760

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
